
GET localhost:7070/api/routes


### -------------- QUESTIONS ROUTES ----------------
###
GET localhost:7070/api/opgave

###
GET localhost:7070/api/opgave/1

###
GET localhost:7070/api/Algebra

###
POST localhost:7070/api/opgave
Content-Type: "application/json"

{
    "id": "1",
    "niveau": "A",
    "termin": "25-03-2025",
    "year": "2025",
    "delprøve": "1",
    "category": "Algebra",
    "author": "Me",
    "license: "None",
    "point": "10",
    "opgavenummer": "1",
    "opgavetekst": "løs opgaven",
    "billede_url": "url",
}

###
PATCH localhost:7070/api/opgave/1
Content-Type: "application/json"

{
    "niveau": "B",
    "opgavenummer": "2",
}

###
DELETE localhost:7070/api/opgave/1


### -------------- ASSIGNMENT ROUTES ----------------
###
GET localhost:7070/api/opgaveset/

###
GET localhost:7070/api/opgaveset/1

###
POST localhost:7070/api/opgaveset
Content-Type: "application/json"

{
    "owner": 1,
    "introText": "String",
    "totalPoints": 10
}

###
PATCH localhost:7070/api/opgaveset/1
Content-Type: "application/json"

{
    "introText": "TEST"
}

###
POST localhost:7070/api/opgaveset/1/add

{
    "id": 1
}

###
POST localhost:7070/api/opgaveset/1/add

{
    "id": 2
}

###
DELETE localhost:7070/api/opgaveset/1/remove

{
    "id": 1
}

###
DELETE localhost:7070/api/opgaveset/1/remove

{
    "id": 2
}

###
DELETE localhost:7070/api/opgaveset/2


### -------------- MATHTEAM ROUTES ----------------
###
GET localhost:7070/api/hold

###
GET localhost:7070/api/hold/1

###
POST localhost:7070/api/hold

{
    "id": Number,
    "owner": UserAccount (id?),
    "desc": String,
    "used_examquestions": [ question, question, ...] (2)
    "assignments": [ assignment_info, assoignment_info, ...] (4)
}

###
POST localhost:7070/api/hold/1/add

###
DELETE localhost:7070/api/hold/1/remove

###
DELETE localhost:7070/api/hold/1


### -------------- USER ROUTES ----------------
###
GET localhost:7070/api/user

###
GET localhost:7070/api/user/1

###
DELETE localhost:7070/api/user/1
