GET localhost:7070/api/routes

###
GET localhost:7070/api/opgave

###
GET localhost:7070/api/opgave/1

###
POST localhost:7070/api/opgave
Content-Type: "application/json"

{
    "id": 1,

    "niveau": A,

    "termin": 25-03-2025,

    "year": 2025,

    "delprøve": 1,

    "category": Algebra,

    "author": Me,

    "licens": None,

    "point": 10,

    "opgavenummer": 1,

    "opgavetekst": løs opgaven,

    "billede_url": url,
}

###
PATCH localhost:7070/api/opgave/1
Content-Type: "application/json"

{
    "name": "Lucky Star Hotel",
    "address": "Brorsonsvej 1"
}

###
DELETE localhost:7070/api/opgave/1

###
GET localhost:7070/api/opgaveset/1